import fs from 'node:fs/promises';
import path from 'node:path';
import { SUPPORTED_EXTENSIONS } from '../utils/videoFormats.js';

const UUID = '[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}';

// Stored names are always "<uuid>.<ext>", generated by the server, with an allow-listed extension.
const STORED_NAME_PATTERN = new RegExp(`^${UUID}\\.(${SUPPORTED_EXTENSIONS.map((e) => e.slice(1)).join('|')})$`);
// Subtitle tracks extracted from a video: "<uuid>.vtt".
const SUBTITLE_NAME_PATTERN = new RegExp(`^${UUID}\\.vtt$`);

function resolveInside(storageDir, name, pattern) {
  if (!pattern.test(name)) {
    throw new Error('Refusing to use an invalid stored filename');
  }
  const root = path.resolve(storageDir);
  const fullPath = path.resolve(root, name);
  if (path.dirname(fullPath) !== root) {
    throw new Error('Resolved path escapes the storage directory');
  }
  return fullPath;
}

/**
 * Turn a stored filename into an absolute path inside the storage directory.
 * Stored names come from our own database, but we still validate them
 * (defence in depth): a name containing "../" or a slash can never escape storageDir.
 */
export const resolveVideoPath = (storageDir, storedName) => resolveInside(storageDir, storedName, STORED_NAME_PATTERN);
export const resolveSubtitlePath = (storageDir, name) => resolveInside(storageDir, name, SUBTITLE_NAME_PATTERN);

export const isStoredVideoName = (name) => STORED_NAME_PATTERN.test(name);
export const isStoredSubtitleName = (name) => SUBTITLE_NAME_PATTERN.test(name);

/** Delete a file, ignoring "already gone". Returns true if nothing is left behind. */
export async function removeFileQuietly(filePath) {
  if (!filePath) return true;
  try {
    await fs.unlink(filePath);
    return true;
  } catch (err) {
    if (err.code === 'ENOENT') return true;
    console.error(`[storage] could not delete ${path.basename(filePath)}: ${err.code}`);
    return false;
  }
}

/** Delete a video's file and all its subtitle files. Returns false if anything was left behind. */
export async function removeVideoFiles(storageDir, video) {
  const results = await Promise.all([
    removeFileQuietly(resolveVideoPath(storageDir, video.storedName)),
    ...(video.subtitles ?? []).map((s) => removeFileQuietly(resolveSubtitlePath(storageDir, s.file))),
  ]);
  return results.every(Boolean);
}
